### ISSUE TITLE
[FEATURE REQUEST] Option to limit size of SVs which are annotated

### ISSUE THREAD

**Issue by jsquaredosquared** [edg1983/GREEN-VARAN#16]
Hi @edg1983, I was wondering if you could consider adding a parameter to set the maximum size of SV to annotate?

Some callers report extremely large SVs which are likely to be spurious (e.g., an inversion with `SVLEN=153641285`). When these large SVs get annotated with all overlapping regulatory regions, the output file can be quite cumbersome. It would be nice if I could choose to annotate only SVs less than 1 Mb, for example.

What do you think?

**Comment by edg1983** [comment]
Hi! 

I didn't include such an option since we usually filter large events (typically SV > 1-2Mb ) as likely false positives in our workflow. The reason for this is that a healthy or non-syndromic individual is unlikely to carry a very large deletion, and these events are thus mostly due to mismapping or artifacts.

You can easily filter your input VCF upstream of the annotation using bcftools and SVLEN INFO tag.

However, I agree that having an additional option to skip annotation for SV above a certain size can be convenient to avoid writing a huge amount of annotation in the VCF. I'll work on it!

**Comment by edg1983** [comment]
Hi!

I've implemented a new `--maxlen` argument in release v1.3.2 that allows you to limit annotations only to SV intervals shorter than the configured threshold. The default is set to 2Mb.

This also improves on SV interval constructions, taking into account CIEND now.

**Comment by jsquaredosquared** [comment]
Awesome. Thanks :D
