### ISSUE TITLE
Only 2 annotated variants in the output of the test vcf

### ISSUE THREAD

**Issue by feliciecos** [edg1983/GREEN-VARAN#2]
Hello! Thank for having developed GREEN-VARAN
I've tried to run the workflow with the test data using:

main.nf  -profile local --input ./test/VCF/GRCh38.test.smallvars.vcf.gz \
--build GRCh38 --\
out results --scores best --regions best --AF \
--greenvaran_config config/prioritize_smallvars.json \
--greenvaran_dbschema config/greendb_schema_v2.5.json

It seems to work (no error message) but when I look at the annotated vcf I've got only two annotated variants whereas the initial vcf contains several thousands of variants. 
I've also tried with a vcf I want to annotate and the output vcf is empty (it contains only the header). 

Do you have an idea of what goes wrong?
Thank you

**Comment by edg1983** [comment]
Hi,
I've just tried to reproduce the error running your same command from the main GREEN-VARAN folder and it worked fine for me (I got an annotated file with 24k vars as expected).
If the workflow is completed correctly, when you look into the results folder you should see a `.vcf.gz` file and also a `.toml` and a `.log` file.
You can open the `.toml` file to see which annotation sources have been configured exactly (each file path is listed in the file as `file=/path/to/file`) and check that the files are actually where expected. In theory if an expected file is missing the workflow would download this for you, but maybe there is a bug in the downloading part explaining your error.
You can then inspect the `.log` file to have an idea of the data used for green-varan itself. The workflow first annotates the VCF using vcfanno and then use this annotated file for green-varan, so if something went wrong during the first step you may see in the green-varan log that the input file has just a few variants.

If you can't see the `.toml` and `.log` files in the results folder then the workflow has not been completed correctly (but I assume it did since you told me no errors were reported).

Let me know what you find so I can help debugging this.

**Comment by feliciecos** [comment]
Hi, 
Thank you for your answer. In my results folder I've got a .toml file and a .log file (attached in this message). The annotation.toml file seems OK but in the log file, it seems that only 2 variants are found in chromosome 1. 
Do you have any idea to debug this?
Thank you ! 
[greenvaran_20220111_091532.log](https://github.com/edg1983/GREEN-VARAN/files/7845254/greenvaran_20220111_091532.log)

**Comment by edg1983** [comment]
Hi,
It seems there are only 2 variants when the annotated file is passed to green-varan...
First, just to be sure, can you check how many variants are in the test input file you have? Just use `bcftools index --nrecords 

Then try this command (it should work from the main GREEN-VARAN folder) to manually run the annotation step and see if there is any error. I assume there is something unexpected going on at this stage so that the intermediate annotated VCF only have 2 vars.
```
GOGC=2000 IRELATE_MAX_CHUNK=10000 IRELATE_MAX_GAP=1000 \
workflow/bin/vcfanno -p 10 tomlfile.toml test/VCF/GRCh38.test.smallvars.vcf.gz \
| bgzip -c > annotated.tmp.vcf.gz
```
By default the local command runs with 10 parallel threads (`-p 10`). So if your local settings have few than this, please try with 10 (the default) and if it fails, then try with a lower sensible value, to check that the issue is not due to multi-threading.  

This will generated an annotated VCF (`annotated.tmp.vcf.gz`) which should contain all the variants seen in the input.

As `tomfile.toml` use the .toml file you have in the results folder.
The `vfcanno` executable is in `workflow/bin` in the GREEN-VARAN tool folder.

**Comment by feliciecos** [comment]
Thank you for your message. 
The test input file contains 24 000 variants.
I've tried the command recommended in your previous message and obtained the following error : 

`=============================================
vcfanno version 0.3.3 [built with go1.16.5]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:116: found 10 sources from 7 files
vcfanno.go:157: falling back to non-bgzip
bix.go:102: warning: data file /gpfs2/well/jknight/felicie/Ressource/greenvaran/GREEN-VARAN-1.0/workflow/../resources/GRCh38/GRCh38_ReMM.tsv.gz is modified more recently than its index.
vcfanno.go:39: using IRELATE_MAX_GAP of 1000
vcfanno.go:39: using IRELATE_MAX_CHUNK of 10000
parallel.go:151: bix: error creating chunked reader from /gpfs2/well/jknight/felicie/Ressource/greenvaran/GREEN-VARAN-1.0/workflow/../resources/GRCh38/GRCh38_ReMM.tsv.gz: EOF
`
So it seems there is a problem with the resource files. 
My GRCh38 folder contains the following files: 
GRCh38_DNase.merged.bed.gz      GRCh38_FATHMM-MKL_NC.tsv.gz.csi  GRCh38_ReMM.tsv.gz      GRCh38_TFBS.merged.bed.gz      GRCh38_UCNE.bed.gz.csi            GRCh38_ncER_perc.bed.gz
GRCh38_DNase.merged.bed.gz.csi  GRCh38_GREEN-DB.bed.gz           GRCh38_ReMM.tsv.gz.1    GRCh38_TFBS.merged.bed.gz.csi  GRCh38_gnomad.genomes.vcf.gz      GRCh38_ncER_perc.bed.gz.csi
GRCh38_FATHMM-MKL_NC.tsv.gz     GRCh38_GREEN-DB.bed.gz.csi       GRCh38_ReMM.tsv.gz.csi  GRCh38_UCNE.bed.gz             GRCh38_gnomad.genomes.vcf.gz.csi

**Comment by edg1983** [comment]
Ok, the problem seems to be a truncated file `GRCh38_ReMM.tsv.gz`. So I assume the download stopped before the end of the file.

I also noticed that you have a `GRCh38_ReMM.tsv.gz.1`  file which likely means you tried to download the ReMM dataset multiple times. I suggest you check the expected file size for ReMM files (and other files as well eventually) compared to the ones in the corresponding repositories listed in `resources/GREENDB_collection.txt`. 

Anyway, thanks for reporting this, since it reveals that this vcfanno error is not captured by nextflow as a failed execution, so I need to implement an additional check on the number of output variants after this step.

Have you downloaded the resource files by your own or were they downloaded automatically by theworkflow? In the latter case it means that a failed download do not result in exit error code by wget, which is useful for me to know. I'm working on implementing an md5 check for downloaded files, but it will take a while to update all the repositories.

**Comment by feliciecos** [comment]
As recommended I've downloaded again (manually)  `GRCh38_ReMM.tsv.gz` file and it works now! Thank you for your suggestion and thank your for having developed this useful tool!

**Comment by edg1983** [comment]
Great to hear it is working now!

Can you confirm that the incomplete download was performed by the Nextflow workflow and that this was completed with no errors apparently? This would mean that wget does not return an error exit code when a download process interrupts unexpectedly and so I need to implement some check on the downloaded files.

I hope GREEN-VARAN will be useful for your research!

**Comment by feliciecos** [comment]
Hi, 
The inital download was performed manually (maybe that's why I didn't have any error message).
