### ISSUE TITLE
greendb_level issue

### ISSUE THREAD

**Issue by LIKUOKUO** [edg1983/GREEN-VARAN#4]
I want to use ​​​​​​GREEN-VARAN workflow​ to annotate regulation variants. Rare variant (population AF < 1%) overlapping one of GREEN-DB regions was defined as ​greendb_level=1, whereas the ​variant with population AF > 1%​  was also defined as ​greendb_level=1​ in my VCF file. Any change of  GREEN-VARAN compare to previous version in your paper?

This is one example:​AC=1;AF=0.125;AN=2;BaseQRankSum=-1.981;DP=18;ExcessHet=3.0103;FS=0;MLEAC=1;MLEAF=0.125;MQ=40;MQRankSum=0;QD=6.73;ReadPosRankSum=0;SOR=0.892;ReMM=0.486;ncER=74.0135;FATHMM_MKLNC=0.9039;TFBS;gnomAD_AF=0.7122;gnomAD_AF_afr=0.3236;gnomAD_AF_amr=0.7951;gnomAD_AF_nfe=0.8539;greendb_id=42036_pro;greendb_stdtype=promoter;greendb_dbsource=ENCODE-HMM;greendb_genes=AL669831.3,OR4F16,CICP3;greendb_level=1;ANN=A|promoter|MODIFIER|CICP3||||||||||||,A|promoter|MODIFIER|AL669831.3||||||||||||,A|promoter|MODIFIER|OR4F16||||||||||||​

**Comment by edg1983** [comment]
Hi,

Indeed there is a slightly difference now in the code compared to published version. Essentially, for a variant overlapping GREEN-DB region(s), GREEN-VARAN now sum up the level of evidence across 4 possible criteria:
- MAF < 1%
- Overlap with functional regions (TFBS, DNase or UCNE)
- One of the configured scores above threshold
- GREEN-DB region constraint > 0.7

So in your case you get level 1 because of additional overlap with TFBS. 

This change was made to better accommodate additional annotations (that you can configure in the config file) and considering that filtering by MAF is something you can easily achieve filtering on the gnomAD AF tags. 

I will update docs to better reflect this change and sorry for the confusion caused.

**Comment by LIKUOKUO** [comment]
I was confused with the annotated results, here is the example which labled as greendb_level=3. But I don't know which three levels satisfy threshold. Was these three levels: MAF<1%; overlap with DNase andTFBS; greendb_constraint=0.722409>0.7. The ReMM=0.538 and ncER=85.5791 were not satisfy FDR50 threshold?
Thank you for your kindly help.
AC=1;AF=0.5;AN=2;BaseQRankSum=0.12;ClippingRankSum=-0;DP=9;ExcessHet=3.0103;FS=7.782;MLEAC=1;MLEAF=0.5;MQ=60;MQRankSum=-0;QD=10.64;ReadPosRankSum=-0;SOR=3.611;VQSLOD=22.3209;culprit=MQ;FATHMM_MKLNC=0.1036;ReMM=0.538;ncER=85.5791;DNase;TFBS;gnomAD_AF=0.005553;gnomAD_AF_afr=0.0053394;gnomAD_AF_amr=0.0048544;gnomAD_AF_nfe=0.0046707;greendb_id=561490_pro,2_biv,505745_pro;greendb_stdtype=bivalent,promoter;greendb_dbsource=FOCS,SegWey,ENCODE-HMM,BENGI,EnsemblRegBuild,FANTOM5;greendb_genes=RBP7;greendb_constraint=0.722409;greendb_level=3;ANN=C|promoter|MODIFIER|RBP7||||||||||||,C|bivalent|MODIFIER|RBP7||||||||||||

**Comment by edg1983** [comment]
Please have a look at version 1.2. In the new version, you can switch between pileup of evidence (as described by my previous comment) and levels mode, which reproduce precisely the mechanism described in the paper (which is essentially a hierarchical passing of the four criteria)
