### ISSUE TITLE
Tissue annotation

### ISSUE THREAD

**Issue by snashraf** [edg1983/GREEN-VARAN#6]
Dear Edoardo,

How we can add and use tissue expression data in annotated VCF file?

Regards,
Najeeb

**Comment by edg1983** [comment]
Hi,

Tissue information can not be added directly into the VCF due to the complexity of this kind of data. The approach we suggest if you want such detailed information is to first filter your variants according to your criteria of interest. When you have selected a reasonable number of candidates  you can use `greenvaran querytab` to generate a table that can be used with `greendb_query -t` to directly query the db and generate tables describing each region and region-gene connection with the tissue where it was detected.

See https://green-varan.readthedocs.io/en/latest/GREEN-DB_query_usage.html

Please keep in mind that tissue information is not standardised in any way, so it reports tissue or cell lines as they were annotated in the source databases.
